### PR TITLE
docs(samples): add samples to create, read, update, and delete products

### PR DESCRIPTION
**Pull request by tetiana-karasova**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-retail/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by parthea** [comment]
HI @tetiana-karasova, Please could you help to resolve the conflicts?

**Comment by tkarasyova** [comment]
the conflicts are resolved

**Comment by parthea** [comment]
Hi @tetiana-karasova,
There is a test failure with `set_inventory_test.py`. Please could you take a look?

```
add_fulfillment_places_test.py .                                         [  9%]
create_product_test.py .                                                 [ 18%]
crud_product_test.py .                                                   [ 27%]
delete_product_test.py .                                                 [ 36%]
get_product_test.py .                                                    [ 45%]
import_products_bq_test.py .                                             [ 54%]
import_products_gcs_test.py .                                            [ 63%]
import_products_inline_test.py .                                         [ 72%]
remove_fulfillment_places_test.py .                                      [ 81%]
set_inventory_test.py F                                                  [ 90%]
update_product_test.py .                                                 [100%]
```

**Review by parthea — DISMISSED** [review]

**Comment by parthea** [comment]
Hi @tetiana-karasova ,
Please could you take a look at the 2 failing tests?
```
add_fulfillment_places_test.py .                                         [  9%]
create_product_test.py .                                                 [ 18%]
crud_product_test.py .                                                   [ 27%]
delete_product_test.py .                                                 [ 36%]
get_product_test.py .                                                    [ 45%]
import_products_bq_test.py .                                             [ 54%]
import_products_gcs_test.py F                                            [ 63%]
import_products_inline_test.py .                                         [ 72%]
remove_fulfillment_places_test.py .                                      [ 81%]
set_inventory_test.py F                                                  [ 90%]
update_product_test.py .                                                 [100%]

=================================== FAILURES ===================================
```

**Review by parthea — APPROVED** [review]

**Pull request merged**
